export const SUPPORTED_EXTENSIONS = [
  "ts",
  "tsx",
  "js",
  "jsx",
  "mjs",
  "cjs",
  "py",
  "go",
  "rs",
  "java",
  "kt",
  "kts",
  "cs",
  "php",
  "rb",
  "swift",
  "vue",
  "svelte",
  "sql",
  "graphql",
  "md",
  "json",
  "yaml",
  "yml",
] as const;

export const IGNORED_GLOBS = [
  "**/.git/**",
  "**/.next/**",
  "**/node_modules/**",
  "**/dist/**",
  "**/build/**",
  "**/out/**",
  "**/coverage/**",
  "**/vendor/**",
  "**/.venv/**",
  "**/venv/**",
  "**/__pycache__/**",
  "**/target/**",
  "**/*.min.js",
  "**/*.map",
  "**/package-lock.json",
  "**/yarn.lock",
  "**/pnpm-lock.yaml",
] as const;

export const INGESTION_LIMITS = {
  maxFiles: 1_000,
  maxFileBytes: 512 * 1024,
  maxRepositoryBytes: 25 * 1024 * 1024,
  maxChunkCharacters: 24_000,
} as const;
